name: Deploy
on:
    push:
        branches: [master]

jobs:
    deploy:
        uses: BijanProgrammerWebsites/hub/.github/workflows/deploy-angular.yml@master
        with:
            host: passaid.ir
            base-href: /
            project-name: passaid
